# Generated by Django 4.0.3 on 2022-03-24 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='particpanties',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
